### ISSUE TITLE
input shape error, occurs for all image chips

### ISSUE THREAD

**Issue by rbavery** [ecohydro/CropMask_RCNN#19]
```
Traceback (most recent call last):
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/model.py", line 1860, in data_generator
    use_mini_mask=config.USE_MINI_MASK,
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/model.py", line 1343, in load_image_gt
    mask = utils.resize_mask(mask, scale, padding, crop)
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/utils.py", line 509, in resize_mask
    mask = scipy.ndimage.zoom(mask, zoom=[scale, scale, 1], order=0)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/scipy/ndimage/interpolation.py", line 595, in zoom
    zoom = _ni_support._normalize_sequence(zoom, input.ndim)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/scipy/ndimage/_ni_support.py", line 65, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank
```

**Comment by rbavery** [comment]
new error, one above is solved but this is related to empty labels but in a different part of the code
```
Traceback (most recent call last):
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/model.py", line 1865, in data_generator
    use_mini_mask=config.USE_MINI_MASK,
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/model.py", line 1402, in load_image_gt
    class_ids = class_ids[_idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 512 but corresponding boolean dimension is 1
ERROR:root:Error processing image {'id': 'tile_4608-1536', 'source': 'landsat', 'path': '/mnt/azureml-filestore-896933ab-f4fd-42b2-a154-0abb35dfb0b0/landsat-1024-cp/train/tile_4608-1536/image/tile_4608-15
36.tif'}
Traceback (most recent call last):
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/model.py", line 1865, in data_generator
    use_mini_mask=config.USE_MINI_MASK,
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/model.py", line 1402, in load_image_gt
    class_ids = class_ids[_idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 512 but corresponding boolean dimension is 1
Added axis to shape of:  (512, 512)
ERROR:root:Error processing image {'id': 'tile_4608-1536', 'source': 'landsat', 'path': '/mnt/azureml-filestore-896933ab-f4fd-42b2-a154-0abb35dfb0b0/landsat-1024-cp/train/tile_4608-1536/image/tile_4608-1536.tif'}

```

**Comment by rbavery** [comment]
Potential Separate error

```
Traceback (most recent call last):
  File "run_cropmask.py", line 343, in <module>
    train(model, args.dataset, args.subset, config)
  File "run_cropmask.py", line 110, in train
    layers="all",
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/model.py", line 2707, in train
    use_multiprocessing=True,
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[117] = 65469 is not in [0, 64512)
         [[{{node ROI/GatherV2_6}}]]
############Image ID 5, mask shape (512, 512, 21) ################

```

**Comment by rbavery** [comment]
more descriptive error. Mask with no instances loses a dim with the indexing which shouldn't happen (third dim goes from 1 to 0)
```
############Image ID 9, mask shape (512, 512, 1) ################
############_idx [False], _idx shape (1,) ################
############ mask shape after _idx (512, 512, 0) ################
############ class_id shape before idx [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] ################
ERROR:root:Error processing image {'id': 'tile_5120-1536', 'source': 'landsat', 'path': '/mnt/azureml-filestore-896933ab-f4fd-42b2-a154-0abb35dfb0b0/landsat-1024-cp/test/tile_5120-1536/image/tile_5120-1536.tif'}
Traceback (most recent call last):
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/model.py", line 1870, in data_generator
    use_mini_mask=config.USE_MINI_MASK,
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/model.py", line 1406, in load_image_gt
    class_ids = class_ids[_idx]

```
