### ISSUE TITLE
attempts to create raster label file fails because dask delayed tries to do this multiple times at once

### ISSUE THREAD

**Issue by rbavery** [ecohydro/CropMask_RCNN#28]
The error message doesn't match up with what I expect is happening, which is a conflict with multiple dask delayed functions trying to open a new tif at the same location. solution is probably to append a scene identifier to each rasterized label subset of the whole label dataset. 

```
(py36) ryan@cropmask-gpu:~/work/CropMask_RCNN/cropmask$ python run_preprocess_many_scenes.py
^[[B^[[B^[[B^[[B^[[B^[[BTraceback (most recent call last):
  File "run_preprocess_many_scenes.py", line 41, in <module>
    labels_path)
  File "run_preprocess_many_scenes.py", line 25, in run_scene_path_list
    dask.compute(*results)
  File "/data/anaconda/envs/py36/lib/python3.6/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/data/anaconda/envs/py36/lib/python3.6/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/data/anaconda/envs/py36/lib/python3.6/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/data/anaconda/envs/py36/lib/python3.6/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/data/anaconda/envs/py36/lib/python3.6/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/data/anaconda/envs/py36/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/data/anaconda/envs/py36/lib/python3.6/site-packages/dask/utils.py", line 772, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/preprocess.py", line 350, in run_single_scene
    self.negative_buffer_and_small_filter(-31, 100)
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/preprocess.py", line 210, in negative_buffer_and_small_filter
    with rasterio.open(self.rasterized_label_path, "w+", **meta) as out:
  File "/data/anaconda/envs/py36/lib/python3.6/site-packages/rasterio/env.py", line 430, in wrapper
    return f(*args, **kwds)
  File "/data/anaconda/envs/py36/lib/python3.6/site-packages/rasterio/__init__.py", line 226, in open
    **kwargs)
  File "rasterio/_io.pyx", line 1131, in rasterio._io.DatasetWriterBase.__init__
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: Attempt to create new tiff file '/permmnt/cropmaskperm/landsat-test/neg_buffered_labels/nebraska_pivots_projected.tif' failed: No such file or directory
```

**Comment by rbavery** [comment]
fixed by renaming rasterized_label with unique scene id
