### ISSUE TITLE
rebuild tensorpack docker image off of aws fork

### ISSUE THREAD

**Issue by rbavery** [ecohydro/CropMask_RCNN#31]
include changes added to armand fork that were pushed to registry

**Comment by rbavery** [comment]
```
Traceback (most recent call last):
  File "/mask-rcnn-tensorflow/MaskRCNN/train.py", line 318, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/mask-rcnn-tensorflow/tensorpack/train/interface.py", line 96, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/mask-rcnn-tensorflow/tensorpack/train/base.py", line 345, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/mask-rcnn-tensorflow/tensorpack/train/base.py", line 315, in train
    self.setup_callbacks(callbacks, monitors)
  File "/mask-rcnn-tensorflow/tensorpack/utils/argtools.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "/mask-rcnn-tensorflow/tensorpack/train/base.py", line 212, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/mask-rcnn-tensorflow/tensorpack/callbacks/base.py", line 55, in setup_graph
    self._setup_graph()
  File "/mask-rcnn-tensorflow/tensorpack/callbacks/group.py", line 72, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/mask-rcnn-tensorflow/tensorpack/callbacks/base.py", line 55, in setup_graph
    self._setup_graph()
  File "/mask-rcnn-tensorflow/MaskRCNN/eval.py", line 356, in _setup_graph
    shard=hvd.local_rank(), num_shards=hvd.local_size(), batch_size=self.batch_size)
  File "/mask-rcnn-tensorflow/MaskRCNN/data.py", line 793, in get_batched_eval_dataflow
    roidbs = DetectionDataset().load_inference_roidbs(name)
  File "/mask-rcnn-tensorflow/MaskRCNN/dataset.py", line 261, in load_inference_roidbs
    return COCODetection.load_many(cfg.DATA.BASEDIR, name, add_gt=False)
  File "/mask-rcnn-tensorflow/MaskRCNN/dataset.py", line 199, in load_many
    ret.extend(coco.load(add_gt, add_mask=add_mask))
  File "/mask-rcnn-tensorflow/MaskRCNN/dataset.py", line 114, in load
    self._use_absolute_file_name(img)
  File "/mask-rcnn-tensorflow/MaskRCNN/dataset.py", line 125, in _use_absolute_file_name
    assert os.path.isfile(img['file_name']), img['file_name']
AssertionError: /data/test/LT050290322005031601T1-SC20190818205024_tile_1024_3072.tif

```

i think because of 

```
index created!
[0924 07:15:02 @dataset.py:49] Instances loaded from /data/annotations/instances_train.json.
100%|██████████| 567/567 [00:15<00:00, 37.17it/s]
[0924 07:15:18 @timer.py:50] Load Groundtruth Boxes for train finished, time:15.2534sec.
Done loading roidbs
[0924 07:15:18 @data.py:509] Filtered 39 images which contain no non-crowd groudtruth boxes. Total #images for training: 528
Batching roidbs
Done batching roidbs
[0924 07:15:20 @trainers.py:393] [HorovodTrainer] local rank=0

```
check is_crowd option in train annotation to make sure all are false.

**Comment by rbavery** [comment]
or, if this is a train id, check why it is being assigned in the test json.

**Comment by rbavery** [comment]
it's definitely that the train paths are being added to the test paths 

```
 11%|█         | 63/567 [00:02<00:22, 22.33it/s]
Traceback (most recent call last):

```

**Comment by rbavery** [comment]
not an issue anymore since I'm using detectron2
